version: '2'

services:

  orderer0.hlftest.com:
    container_name: orderer0.hlftest.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../../crypto-config/ordererOrganizations/hlftest.com/orderers/orderer0.hlftest.com/msp:/var/hyperledger/orderer/msp
        - ../../crypto-config/ordererOrganizations/hlftest.com/orderers/orderer0.hlftest.com/tls/:/var/hyperledger/orderer/tls
        - orderer0.hlftest.com:/var/hyperledger/production/orderer
    ports:
      - 6050:6050

  peer0.org0.hlftest.com:
    container_name: peer0.org0.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org0.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org0.hlftest.com:6051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org0.hlftest.com:6052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org0.hlftest.com:6051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org0.hlftest.com:6051
      - CORE_PEER_LOCALMSPID=Org0MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org0.hlftest.com/peers/peer0.org0.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org0.hlftest.com/peers/peer0.org0.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org0.hlftest.com:/var/hyperledger/production
    ports:
      - 6051:6051

  peer0.org1.hlftest.com:
    container_name: peer0.org1.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org1.hlftest.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.hlftest.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.hlftest.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.hlftest.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org1.hlftest.com/peers/peer0.org1.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org1.hlftest.com/peers/peer0.org1.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.hlftest.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.org2.hlftest.com:
    container_name: peer0.org2.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org2.hlftest.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.hlftest.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.hlftest.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.hlftest.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org2.hlftest.com/peers/peer0.org2.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org2.hlftest.com/peers/peer0.org2.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.hlftest.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.org3.hlftest.com:
    container_name: peer0.org3.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org3.hlftest.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.hlftest.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.hlftest.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.hlftest.com:9051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org3.hlftest.com/peers/peer0.org3.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org3.hlftest.com/peers/peer0.org3.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.hlftest.com:/var/hyperledger/production
    ports:
      - 9051:9051
  
  peer0.org4.hlftest.com:
    container_name: peer0.org4.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org4.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org4.hlftest.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.hlftest.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.hlftest.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.hlftest.com:10051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org4.hlftest.com/peers/peer0.org4.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org4.hlftest.com/peers/peer0.org4.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org4.hlftest.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.org5.hlftest.com:
    container_name: peer0.org5.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org5.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org5.hlftest.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org5.hlftest.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org5.hlftest.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org5.hlftest.com:11051
      - CORE_PEER_LOCALMSPID=Org5MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org5.hlftest.com/peers/peer0.org5.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org5.hlftest.com/peers/peer0.org5.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org5.hlftest.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer0.org6.hlftest.com:
    container_name: peer0.org6.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org6.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org6.hlftest.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org6.hlftest.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org6.hlftest.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org6.hlftest.com:12051
      - CORE_PEER_LOCALMSPID=Org6MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org6.hlftest.com/peers/peer0.org6.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org6.hlftest.com/peers/peer0.org6.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org6.hlftest.com:/var/hyperledger/production
    ports:
      - 12051:12051

  peer0.org7.hlftest.com:
    container_name: peer0.org7.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org7.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org7.hlftest.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org7.hlftest.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org7.hlftest.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org7.hlftest.com:13051
      - CORE_PEER_LOCALMSPID=Org7MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org7.hlftest.com/peers/peer0.org7.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org7.hlftest.com/peers/peer0.org7.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org7.hlftest.com:/var/hyperledger/production
    ports:
      - 13051:13051

  peer0.org8.hlftest.com:
    container_name: peer0.org8.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org8.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org8.hlftest.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org8.hlftest.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org8.hlftest.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org8.hlftest.com:14051
      - CORE_PEER_LOCALMSPID=Org8MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org8.hlftest.com/peers/peer0.org8.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org8.hlftest.com/peers/peer0.org8.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org8.hlftest.com:/var/hyperledger/production
    ports:
      - 14051:14051

  peer0.org9.hlftest.com:
    container_name: peer0.org9.hlftest.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org9.hlftest.com
      - CORE_PEER_ADDRESS=peer0.org9.hlftest.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org9.hlftest.com:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org9.hlftest.com:15051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org9.hlftest.com:15051
      - CORE_PEER_LOCALMSPID=Org9MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org9.hlftest.com/peers/peer0.org9.hlftest.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org9.hlftest.com/peers/peer0.org9.hlftest.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org9.hlftest.com:/var/hyperledger/production
    ports:
      - 15051:15051
