OrdererOrgs:
  # Orderer
  - Name: Orderer
    Domain: hlftest.com
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5
      - Hostname: orderer6
      - Hostname: orderer7
      - Hostname: orderer8
      - Hostname: orderer9
# Peers Orgs
PeerOrgs:
  # Org0
  - Name: Org0
    Domain: org0.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org1
  - Name: Org1
    Domain: org1.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org2
  - Name: Org2
    Domain: org2.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org3
  - Name: Org3
    Domain: org3.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org4
  - Name: Org4
    Domain: org4.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org5
  - Name: Org5
    Domain: org5.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org6
  - Name: Org6
    Domain: org6.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org7
  - Name: Org7
    Domain: org7.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org8
  - Name: Org8
    Domain: org8.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org9
  - Name: Org9
    Domain: org9.hlftest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
