version: '2'

volumes:
  orderer5.hlftest.com:
  peer0.org5.hlftest.com:

networks:
  hlftest_network:
    external:
      name: ${NETWORK_NAME}

services:

  orderer5.hlftest.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=11050
    container_name: orderer5.hlftest.com
    networks:
    - hlftest_network
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hlftest.com/orderers/orderer5.hlftest.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hlftest.com/orderers/orderer5.hlftest.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.hlftest.com:/var/hyperledger/production/orderer
    ports:
    - 11050:11050

  peer0.org5.hlftest.com:
    container_name: peer0.org5.hlftest.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org5.hlftest.com
    networks:
      - hlftest_network

