version: '2'

volumes:
  orderer0.hlftest.com:
  peer0.org0.hlftest.com:

networks:
  hlftest_network:
    external:
      name: ${NETWORK_NAME}

services:

  orderer0.hlftest.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.hlftest.com
    environment:
      - ORDERER_GENERAL_LISTENPORT=6050
    container_name: orderer0.hlftest.com
    networks:
      - hlftest_network
    ports:
    - 6050:6050

  peer0.org0.hlftest.com:
    container_name: peer0.org0.hlftest.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org0.hlftest.com
    networks:
      - hlftest_network

  